[websocket]
listen = "127.0.0.1:8080"
ws_path = "/ws"
health_path = "/healthz"
heartbeat_interval_secs = 180
heartbeat_timeout_secs = 600
max_clients = 1024
client_buffer_size = 1024

[substreams]
endpoint = "https://solana.substreams.pinax.network:443"
network = "solana-mainnet"
stop_block = "0"
production_mode = false
final_blocks_only = false

[[streams]]
name = "swaps"
manifest = "https://github.com/pinax-network/substreams-svm/releases/download/svm-dex-v0.5.1/dex-swaps-v0.5.1.spkg"
module = "map_events"

[[streams]]
name = "transfers"
manifest = "https://github.com/pinax-network/substreams-svm/releases/download/svm-transfers-v0.3.0/spl-token-v0.3.0.spkg"
module = "map_events"
